server:
  port: 8131

spring:
  application:
    name: card-management-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.omnibank.cardmanagement: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: com.omnibank.cardmanagement.api

card-management:
  eventPublisher: logging  # switch to 'kafka' when Kafka broker is available
  events:
    topic: card.management.events
