server:
  port: 8102

spring:
  application:
    name: customer-profile-service
  datasource:
    url: jdbc:h2:mem:customer_profile;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.omnibank.customerprofile: DEBUG
