server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/faihussa/Downloads/projectbanking/bank-config-repo
  application:
    name: config-server
