server:
  port: 8103

spring:
  application:
    name: account-management-service
  datasource:
    url: jdbc:h2:mem:account_master;DB_CLOSE_DELAY=-1;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:}
    consumer:
      group-id: account-management
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.omnibank.accountmanagement: DEBUG

# Feature flags and topics for eventing
account:
  kafka:
    enabled: false   # set to true to enable Kafka consumer for ledger.events
  events:
    topic: account.events
    ledgerTopic: ledger.events
