spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest

# Enable Kafka consumer for ledger.events
account:
  kafka:
    enabled: true
  events:
    topic: account.events
    ledgerTopic: ledger.events
