spring:
  application:
    name: account-management-service

# Minimal local secure profile (no external IdP)
account-management:
  security:
    # Default dev admin token; override via env ADMIN_BEARER_TOKEN
    adminBearerToken: ${ADMIN_BEARER_TOKEN:admin-token-dev}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.omnibank.accountmanagement: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: com.omnibank.accountmanagement.api
