spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest

payment-gateway:
  # Enable Kafka publisher and async orchestration
  eventPublisher: kafka
  # In Kafka async mode, gateway should not synchronously post to ledger
  devSyncPosting: false
  # Disable any dev balance adjustments; balances will update via ledger.events
  devBalanceAdjustEnabled: false
  kafka:
    enabled: true
  events:
    ledgerTopic: ledger.events
