server:
  port: 8120

spring:
  application:
    name: loan-origination-service
  # Exclude Mongo autoconfiguration for dev-local (no Docker/Mongo required).
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
    com.omnibank.loanorigination: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
  packages-to-scan: com.omnibank.loanorigination.api

loan-origination:
  events:
    topic: loan.origination.events
  eventPublisher: logging  # switch to 'kafka' when Kafka broker is available

resilience4j:
  circuitbreaker:
    instances:
      accountManagement:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  retry:
    instances:
      accountManagement:
        maxAttempts: 3
        waitDuration: 200ms
  bulkhead:
    instances:
      accountManagement:
        maxConcurrentCalls: 30
        maxWaitDuration: 0
      paymentGateway:
        maxConcurrentCalls: 10
        maxWaitDuration: 0
